# Generated by Django 5.0.2 on 2024-04-18 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Organigrama", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organigrama",
            name="apellido_a",
        ),
        migrations.RemoveField(
            model_name="organigrama",
            name="apellido_m",
        ),
        migrations.RemoveField(
            model_name="organigrama",
            name="password",
        ),
        migrations.RemoveField(
            model_name="organigrama",
            name="usuario",
        ),
        migrations.AlterModelTable(
            name="organigrama",
            table="usuario2",
        ),
    ]
